### ISSUE TITLE
Output PDF has loss of data

### ISSUE THREAD

**Issue by zain910128** [py-pdf/pypdf#1607] opened 2023-02-04 23:22 UTC
I am using the following code to resize pages in a PDF:

```python
from pypdf import PdfReader, PdfWriter, Transformation, PageObject, PaperSize
from pypdf.generic import RectangleObject

reader = PdfReader("input.pdf")
writer = PdfWriter()
for page in reader.pages:
    A4_w = PaperSize.A4.width
    A4_h = PaperSize.A4.height

    # resize page to fit *inside* A4
    h = float(page.mediabox.height)
    w = float(page.mediabox.width)
    scale_factor = min(A4_h / h, A4_w / w)

    transform = (
        Transformation()
        .scale(scale_factor, scale_factor)
        .translate(0, A4_h / 2 - h * scale_factor / 2)
    )
    page.add_transformation(transform)

    page.cropbox = RectangleObject((0, 0, A4_w, A4_h))

    # merge the pages to fit inside A4

    # prepare A4 blank page
    page_A4 = PageObject.create_blank_page(width=A4_w, height=A4_h)
    page.mediabox = page_A4.mediabox
    page_A4.merge_page(page)

    writer.add_page(page_A4)
writer.write("output.pdf")
```

Source: https://stackoverflow.com/a/75274841/11501160

While this code works fine for the resizing part, I have found that most input files work fine but some input files do not work fine.

I am providing download links to [input.pdf](https://drive.google.com/file/d/1aQ8xEeQUq4gA3Ugn73Ed-dy_Dt5TFC-a/view?usp=sharing) and [output.pdf](https://drive.google.com/file/d/1sV9P5m0_ItPzF0VL_lkCHzMZPE2LkpRJ/view?usp=sharing) files for testing and review. The output file is completely different from the input file. The images are missing, the background colour is different, even the pure text on first page has only the first line visible.

What is interesting is that these difference are only seen when I open the output pdf in Adobe Acrobat, or look at the physically printed pages. The PDF looks perfect when i open in Preview (on MacOS) or open the PDF in my Chrome Browser.

![screenshot of input file](https://user-images.githubusercontent.com/31308724/216793640-7f1c00bc-2f7a-4dd4-b2bd-a5e9c1f3c58e.jpg)

and

<img width="541" alt="screenshot of output file" src="https://user-images.githubusercontent.com/31308724/216793645-13530f92-1309-4872-ac1e-05ea9cf4d7aa.png">

The origin of the input pdf is that I created it in Preview (on MacOS) by mixing pages from different PDFs and dragging image files into the thumbnails as per these instructions: https://support.apple.com/en-ca/HT202945 I've never had a problem before while making PDFs like this and even Adobe Acrobat reads the input pdf properly. Only the output pdf is problematic in Acrobat and in printers.

Is this a bug with pypdf or am I doing something wrong ? How can i get the output PDF to be proper in Adobe Acrobat and printers etc ?

**Comment by mrknwk** [comment] 2023-02-05 00:18
This is indeed a pypdf bug which occurs since version 2.10.9. The problem will be fixed with tomorrow's update to version 3.3.1 (PR https://github.com/py-pdf/pypdf/pull/1563).

When PDF pages are transformed with non-integer values, this results in floating point numbers with a precision of more than 19 decimal places. Unlike other PDF viewers, Acrobat cannot handle this. See Github issues https://github.com/py-pdf/pypdf/issues/1376 and https://github.com/py-pdf/pypdf/issues/1527 for a detailed discussion.

**Comment by pubpub-zz** [comment] 2023-02-07 21:04
@zain910128 
Can you confirm this PR can now be closed?

**Comment by pubpub-zz** [comment] 2023-02-12 11:46
I close this issue as Fixed. @zain910128 feel free to provide more info if you want to re open it

**Comment by zain910128** [comment] 2023-02-13 03:02
Sorry, i didn't get the chance to check earlier.
But I checked it now and the issue is partially resolved. 

The original input file that i provided is now converted properly and looks fine in all PDF viewers.

Then i tried with a new input file which is very similar and has one extra page. Attached here for reference:
[input.pdf](https://github.com/py-pdf/pypdf/files/10718225/input.pdf)


The output of this file has colours all wrong in mac's Preview and google drive and the browser's pdf viewer, but fine in Adobe acrobat.

So I think we have to reopen this issue.

This may be related to my other issue here:
https://github.com/py-pdf/pypdf/issues/1615

**Comment by pubpub-zz** [comment] 2023-02-13 17:10
The latest inputs look like a duplicate of #1615
@MartinThoma  I propose to close it here and just keep track in  #1615

**Comment by MartinThoma** [comment] 2023-02-13 21:27
That's fine for me :-) I also had the feeling the issue was duplicated :-)

**Closed by MartinThoma** 2023-02-13 21:27 UTC
Labels: is-bug
