### ISSUE TITLE
Memory leak when reading a file

### ISSUE THREAD

**Issue by mr-st0rm** [py-pdf/pypdf#2141] opened 2023-09-03 05:24 UTC
Replace this: What happened? What were you trying to achieve?

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m venv venv

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf2 3.0.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from PyPDF2 import PdfWriter, PdfReader

def _add_watermark_to_doc(
        input_pdf_path: str, watermark: str, message
) -> str:
    output_pdf = PdfWriter()
    filename = f"./src/files/{int(time.time())}.pdf"

    watermark_pdf = PdfReader(f"./src/watermarks/{watermark}")
    watermark_page = watermark_pdf.pages[0]

    orig_file = PdfReader(input_pdf_path)

    for page in orig_file.pages:
        watermark_page.scale_to(
            width=float(page.mediabox.width),
            height=float(page.mediabox.height)
        )

        new_page = page
        new_page.merge_page(watermark_page, expand=True)

        new_page.compress_content_streams()

        output_pdf.add_page(new_page)

    with open(filename, "wb") as result:
        output_pdf.write(result)

    return filename

```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete Traceback I see:

```
I make like that
import tracemalloc

tracemalloc.start()

document_with_watermark = _add_watermark(path, watermark)

snapshot = tracemalloc.take_snapshot()
top_stats = snapshot.statistics('lineno')

for stat in top_stats[:10]:
    print(f"tracemalloc - {stat}")
---------------------------------------------------------------------------------
And result is 
tracemalloc - \venv\lib\site-packages\PyPDF2\generic\_data_structures.py:430: size=45.9 MiB, count=2434, average=19.3 KiB
tracemalloc - \venv\lib\site-packages\PyPDF2\generic\_base.py:616: size=677 KiB, count=11772, average=59 B
tracemalloc - \venv\lib\site-packages\PyPDF2\generic\_base.py:227: size=508 KiB, count=9997, average=52 B
......
![image](https://github.com/py-pdf/pypdf/assets/48455163/2e756c7d-14cb-4194-818c-ad14f5c16771)

and I repeat it, for sure in result
tracemalloc - \venv\lib\site-packages\PyPDF2\generic\_data_structures.py:430: size=45.9 MiB, count=2434, average=19.3 KiB
tracemalloc - \venv\lib\site-packages\PyPDF2\generic\_base.py:616: size=677 KiB, count=11772, average=59 B
tracemalloc - \venv\lib\site-packages\PyPDF2\generic\_base.py:227: size=508 KiB, count=10007, average=52 B
--------------------------------------------------------------------------------
i try make something like this

    try:
        watermark_pdf.stream.close()
        orig_file.stream.close()
        orig_file.__dict__.clear()
        watermark_page.__dict__.clear()
        output_pdf.__dict__.clear()

        watermark_pdf = None
        orig_file = None
        output_pdf = None
    finally:
        os.remove(input_pdf_path)

    gc.collect()

and it helps me now, but i think it's not normal
```

**Comment by mr-st0rm** [comment] 2023-09-03 05:26
my system is Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-60-generic x86_64)
on Windows 10 it's like that, but better a little bit

**Comment by pubpub-zz** [comment] 2023-09-03 06:53
@mr-st0rm can you please provide the pdf showing the behavior
Also at first sight I see one thing : you are only doing a rescaling in the loop. This means that you are accumulating in the content the rescaling lines every turn. You may have to move the line 
```
watermark_pdf = PdfReader(f"./src/watermarks/{watermark}")
watermark_page = watermark_pdf.pages[0]
```
inside the loop

**Comment by mr-st0rm** [comment] 2023-09-03 06:59
i can't share throw here, cz limit 25mb
here's the link for my original file https://docdro.id/Fa7G4Cd

and my watermark file
[202337.pdf](https://github.com/py-pdf/pypdf/files/12505327/202337.pdf)

**Comment by mr-st0rm** [comment] 2023-09-03 07:03
> watermark_pdf = PdfReader(f"./src/watermarks/{watermark}")
> watermark_page = watermark_pdf.pages[0]
> ```
> 
> inside the loop

yeap, i do this now, tnx, but not helped
so on start python take ~88mb of RAM
at the end of process one file it shows ~192mb(file size is like ~47mb)

so, i think that content is in reader and writer still in RAM after exit from function

**Comment by pubpub-zz** [comment] 2023-09-03 07:09
What can occur also to prevent reuse of the "pointers" with invalid data, a link between the writer and the reader source.To break manually this link call `output_pdf.reset_translation()` (see https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html?highlight=clone#reset-translation) Do you see improvements ?

**Comment by mr-st0rm** [comment] 2023-09-03 07:27
> 

unfortunately there are no changes

**Comment by pubpub-zz** [comment] 2023-09-03 19:17
@mr-st0rm 
a) can you provide the test files. 
b) Also you seem to be more efficient than I am about memory mesurement, can you try to run on only one page and try to identify which function call introduces this growth.

**Comment by mr-st0rm** [comment] 2023-09-04 06:12
> @mr-st0rm a) can you provide the test files. b) Also you seem to be more efficient than I am about memory mesurement, can you try to run on only one page and try to identify which function call introduces this growth.

1. https://github.com/py-pdf/pypdf/issues/2141#issuecomment-1704030225 
here test file and watermark file

**Comment by pubpub-zz** [comment] 2023-09-22 14:38
@mr-st0rm 
any update?

**Comment by MartinThoma** [comment] 2023-09-24 10:00
I'm closing this issue for multiple reasons

1. No test file is provided + nobody here is able to reproduce the issue
2. It seems to be about PyPDF2. We are only updating pypdf.

**Closed by MartinThoma** 2023-09-24 10:00 UTC
