### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'NameObject'

### ISSUE THREAD

**Issue by james811223ad** [py-pdf/pypdf#2013] opened 2023-07-25 16:47 UTC
I tried calling PdfReader on a pdf, but got the error.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-4.14.314-164.539.amzn1.x86_64-x86_64-with-glibc2.17

$ python -c "import pypdf;print(pypdf.__version__)"
3.13.0
```

## Traceback

This is the complete Traceback I see:

entry 5928 in Xref table invalid but object found
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[36], line 1
----> 1 PdfReader('temp/t.pdf')

File ~/SageMaker/custom-miniconda/miniconda/envs/py311/lib/python3.11/site-packages/pypdf/_reader.py:326, in PdfReader.__init__(self, stream, strict, password)
    324     with open(stream, "rb") as fh:
    325         stream = BytesIO(fh.read())
--> 326 self.read(stream)
    327 self.stream = stream
    329 self._override_encryption = False

File ~/SageMaker/custom-miniconda/miniconda/envs/py311/lib/python3.11/site-packages/pypdf/_reader.py:1548, in PdfReader.read(self, stream)
   1545     logger_warning(f"incorrect startxref pointer({xref_issue_nr})", __name__)
   1547 # read all cross reference tables and their trailers
-> 1548 self._read_xref_tables_and_trailers(stream, startxref, xref_issue_nr)
   1550 # if not zero-indexed, verify that the table is correct; change it if necessary
   1551 if self.xref_index and not self.strict:

File ~/SageMaker/custom-miniconda/miniconda/envs/py311/lib/python3.11/site-packages/pypdf/_reader.py:1758, in PdfReader._read_xref_tables_and_trailers(self, stream, startxref, xref_issue_nr)
   1756     x = stream.read(1)
   1757 if x == b"x":
-> 1758     startxref = self._read_xref(stream)
   1759 elif xref_issue_nr:
   1760     try:

File ~/SageMaker/custom-miniconda/miniconda/envs/py311/lib/python3.11/site-packages/pypdf/_reader.py:1794, in PdfReader._read_xref(self, stream)
   1793 def _read_xref(self, stream: StreamType) -> Optional[int]:
-> 1794     self._read_standard_xref_table(stream)
   1795     read_non_whitespace(stream)
   1796     stream.seek(-1, 1)

File ~/SageMaker/custom-miniconda/miniconda/envs/py311/lib/python3.11/site-packages/pypdf/_reader.py:1661, in PdfReader._read_standard_xref_table(self, stream)
   1659 stream.seek(-1, 1)
   1660 cnt = 0
-> 1661 while cnt < size:
   1662     line = stream.read(20)
   1664     # It's very clear in section 3.4.3 of the PDF spec
   1665     # that all cross-reference table lines are a fixed
   1666     # 20 bytes (as of PDF 1.7). However, some files have
   1667     # 21-byte entries (or more) due to the use of \r\n
   1668     # (CRLF) EOL's. Detect that case, and adjust the line
   1669     # until it does not begin with a \r (CR) or \n (LF).

TypeError: '<' not supported between instances of 'int' and 'NameObject'

## Note

I can't share the pdf.

**Comment by pubpub-zz** [comment] 2023-07-25 17:03
Without the pdf we can not come to any analysis. Would you agree to share it privately by mail with @MartinThoma  : info@martin-thoma.de?

**Comment by james811223ad** [comment] 2023-07-25 18:28
I can't because of NDA. It's ok if you can't investigate without the pdf. Thanks!

**Comment by pubpub-zz** [comment] 2023-07-25 18:36
My recommandation : using pdb, try to identify the content of size and locate it using a binary viewer. Meanwhile I will close this issue. Feel free to ask to reopen it if you have more data to provide

**Closed by pubpub-zz** 2023-07-25 18:36 UTC

**Comment by tsclausing** [comment] 2024-04-01 17:56
This error happened in our system recently with a user submitted PDF. Unfortunately I am also not able to provide the PDF.

Root cause?

The condition for this error can be reproduced in a test by setting first line of the `xref` representing the number of entries to a value 1 greater than the actual number of entries, which was the case in the PDF we observed. This causes the first bytes of the `trailer` to be read as an xref entry instead of as the break condition for the `_read_standard_xref_table()` method's outer loop.

The specific `TypeError: '<' not supported between instances of 'int' and 'NameObject'` happens when the next bytes read by `size = cast(int, read_object(stream, self))` happen to return a `NameObject` from the trailer, such as `/Root`, though this won't always be the case.

Potential solutions?

* Do nothing, this is an exception that should not be tested for and handled?
* Handle this scenario with a helpful error message?
* Don't trust the xref size; check for the `trailer` on each xref entry and break when found, perhaps logging a warning?

Curious to hear other thoughts, and happy to help if this is worthy of a fix and test case.

**Comment by stefan6419846** [comment] 2024-04-01 18:00
Could you please check if this is still reproducible with the latest *main* branch (we had some unreleased xref changes)? Otherwise, please consider opening a new issue and propose a PR if you like/are able to.

**Comment by tsclausing** [comment] 2024-04-01 20:00
Thank you so much for the reply! The error itself appears to be reproducible on the latest `main` branch, and when this fails I do see a helpful log output as well:

```
WARNING  pypdf._reader:_utils.py:467 entry 6 in Xref table invalid; object not found
```

Following the examples in `test_reader.py` and using a `pdf_data` value with an xref portion similar to the following will create the conditions for the error: the xref size is 6 and there are 5 entries.

```python
        ...
        b"xref 0 6\n"
        b"%010d 00000 n\n"
        b"%010d 00000 n\n"
        b"%010d 00000 n\n"
        b"%010d 00000 n\n"
        b"%010d 00000 n\n"
        b"trailer ... 
```

It's not clear to me that any changes are required, unless it is preferable for the trailer to be detected and the method to return. Is the best next step in this case a new issue?

**Comment by stefan6419846** [comment] 2024-04-02 04:54
Yes, I would recommend opening a new issue for this to cleanly discuss this.
