### ISSUE TITLE
ImportError: cannot import name 'PdfReader' from partially initialized module 'pypdf'

### ISSUE THREAD

**Issue by zaheerkzz** [py-pdf/pypdf#1577] opened 2023-01-24 09:08 UTC
ImportError: cannot import name 'PdfReader' from partially initialized module 'pypdf' (most likely due to a circular import) 

## Environment : VSCode

Which environment were you using when you encountered the problem?
Windows 11
```bash
$ python -m platform : 3.8.10
# TODO: Your output goes here

$ python -c "import pypdf;print(pypdf.__version__)"
ImportError: cannot import name 'PdfReader' from partially initialized module 'pypdf' (most likely due to a circular import) 
```

**Comment by MartinThoma** [comment] 2023-01-24 18:04
I have an idea what might have happened. You might have chosen a bad script name (e.g. `pypdf.py` / `PdfReader.py` or similar). If there is a py / pyc file with that name, it might cause this issue.

@zaheerkzz Please try the following:

```python
$ mkdir issue-1577
$ cd issue-1577
$ python -m venv venv
$ source venv/bin/activate
$ pip install pypdf
$ python -c "import pypdf;print(pypdf.__version__)"
```

**Comment by pubpub-zz** [comment] 2023-01-31 18:45
@zaheerkzz any update ?

**Comment by MartinThoma** [comment] 2023-02-02 20:06
I'm closing this issue as the cause is likely not in pypdf.

**Closed by MartinThoma** 2023-02-02 20:06 UTC

**Comment by fawern** [comment] 2024-08-26 08:02
> ImportError: cannot import name 'PdfReader' from partially initialized module 'pypdf' (most likely due to a circular import)
> 
> ## Environment : VSCode
> Which environment were you using when you encountered the problem? Windows 11
> 
> ```shell
> $ python -m platform : 3.8.10
> # TODO: Your output goes here
> 
> $ python -c "import pypdf;print(pypdf.__version__)"
> ImportError: cannot import name 'PdfReader' from partially initialized module 'pypdf' (most likely due to a circular import) 
> ```

You can use PdfFileReader for older PyPDF2 than  2.x.x

**Comment by pubpub-zz** [comment] 2024-08-26 08:20
@fawern 
PyPDF2 is no more supported.
PdfReader should be used instead of PdfFileReader in pypdf.

**Comment by fawern** [comment] 2024-08-26 08:38
I use it with PyPDF2 version '1.26.0' , and it works

**Comment by pubpub-zz** [comment] 2024-08-26 08:44
as said PyPDF2 is no more supported.
