### ISSUE TITLE
transfer_rotation_to_content and annotations

### ISSUE THREAD

**Issue by kwang-yong-hyun** [py-pdf/pypdf#2784] opened 2024-08-02 05:57 UTC
## Explanation

I'm trying to create an N-up function. 

If there are vertically long pages in the pdf document, first rotate them 90 degrees and then use "merge_translated_page". 

![1](https://github.com/user-attachments/assets/9641563c-943a-4001-8f0f-9ce730365f84)

page.rotate(90)

![2](https://github.com/user-attachments/assets/9cea7d95-a003-4830-8f0c-30e1b14ddd2f)

"transfer_rotation_to_content" was applied to fix rotated pages. 

page.transfer_rotation_to_content()

![3](https://github.com/user-attachments/assets/3bc2be16-0a12-4ffe-bf0f-5c951c19774b)

The angle of the content has been fixed, but the annotation has returned to its original angle.

There is something similar in "merge_translated_page".

new_page.merge_translated_page(page, margin_left ,paper_height - (margin_top + page_height))

![4](https://github.com/user-attachments/assets/79f40b17-a381-4497-8a95-404b67201c00)

I asked Chatgpt how to move  annotations and found the answer.

annotations = page.get("/Annots")

if annotations:
    for annotation in annotations:
        annotation_obj = annotation.get_object()
        rect = annotation_obj.get("/Rect")
        if rect:
            rect[0] = FloatObject(rect[0] +(margin_left))  
            rect[1] = FloatObject(rect[1] +paper_height - (margin_top + page_height))  
            rect[2] = FloatObject(rect[2] +(margin_left)) 
            rect[3] = FloatObject(rect[3] +paper_height - (margin_top + page_height))  

            annotation_obj.update({
                "/Rect": ArrayObject(rect)
            })

![5](https://github.com/user-attachments/assets/d3318396-9e6b-49d4-8d13-c0b3cfac1def)

Looking at these things, I think that "pypdf" is fully capable of changing the location of annotations.

In the next update I hope that the annotations will also be moved along with the contents.

**Comment by stefan6419846** [comment] 2024-08-02 06:00
This is a duplicate of #2592, thus I am going to close this issue in favor of the original report.

**Closed by stefan6419846** 2024-08-02 06:00 UTC
