### ISSUE TITLE
LICENSE can't be consistently looked up due to spdx_id: "NOASSERTION"

### ISSUE THREAD

**Issue by oaustegard** [py-pdf/pypdf#2261] opened 2023-10-21 03:27 UTC
See https://api.github.com/repos/py-pdf/PyPDF2/license which redirects to https://api.github.com/repositories/3119517/license: 
``` json
{
  "name": "LICENSE",
  "path": "LICENSE",
  "sha": "ab327d0312875458ba74983867f1b2622b6de39d",
  "size": 1605,
  "url": "https://api.github.com/repos/py-pdf/pypdf/contents/LICENSE?ref=main",
  "html_url": "https://github.com/py-pdf/pypdf/blob/main/LICENSE",
  "git_url": "https://api.github.com/repos/py-pdf/pypdf/git/blobs/ab327d0312875458ba74983867f1b2622b6de39d",
  "download_url": "https://raw.githubusercontent.com/py-pdf/pypdf/main/LICENSE",
  "type": "file",
  "content": "Q29weXJpZ2h0I...NIIERBTUFHRS4K\n",
  "encoding": "base64",
  "_links": {
    "self": "https://api.github.com/repos/py-pdf/pypdf/contents/LICENSE?ref=main",
    "git": "https://api.github.com/repos/py-pdf/pypdf/git/blobs/ab327d0312875458ba74983867f1b2622b6de39d",
    "html": "https://github.com/py-pdf/pypdf/blob/main/LICENSE"
  },
  "license": {
    "key": "other",
    "name": "Other",
    "spdx_id": "NOASSERTION",
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  }
}
```
Note that the urls are all also for the non-v2 version

**Comment by stefan6419846** [comment] 2023-10-21 06:21
Could you please provide some more information on what you are trying to achieve? It seems like the GitHub license text parser fails to identify our license. You might consider relying on the Python package metadata instead which does not depend on external license parsers.

**Comment by pubpub-zz** [comment] 2023-10-21 07:38
@oaustegard  
PyPDF2 is no more supported and maintained. please check on pypdf if the issue is still valid. If not we will close it

**Comment by oaustegard** [comment] 2023-10-21 12:04
That’s actually where this started: it was unavailable from https://pypi.org/pypi/PyPDF2/json but my parser found the github repo and then tried that api. I might need to alter the parser to check Anaconda (where it IS specified) before GitHub but clearly could also be a problem for others doing license scanning for one reason or another On Oct 21, 2023, at 2:21 AM, Stefan ***@***.***> wrote:﻿
Could you please provide some more information on what you are trying to achieve? It seems like the GitHub license text parser fails to identify our license. You might consider relying on the Python package metadata instead which does not depend on external license parsers.

**Comment by oaustegard** [comment] 2023-10-21 12:05
Oh, so I’m using an old version! — good to know! Thanks!On Oct 21, 2023, at 3:38 AM, pubpub-zz ***@***.***> wrote:﻿
@oaustegard
PyPDF2 is no more supported and maintained. please check on pypdf if the issue is still valid. If not we will close it

**Closed** 2023-10-21 12:06 UTC

**Comment by stefan6419846** [comment] 2023-10-21 12:24
> That’s actually where this started: it was unavailable from https://pypi.org/pypi/PyPDF2/json but my parser found the github repo and then tried that api.

The PyPI JSON API returns the license as well, but only as part of the trove classifiers list, which you could parse (and is done by Python-specific tools like `pip-licenses` as well). This seems due to a limitation of `pyproject.toml` configuration files which either allow a file or name for the license, but not both: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#license https://github.com/py-pdf/pypdf/blob/9047079045742f09df1a2f5ff40d4b316ec35f7a/pyproject.toml#L12

> I might need to alter the parser to check Anaconda (where it IS specified) before GitHub but clearly could also be a problem for others doing license scanning for one reason or another

License scanning is a complex topic with lots of pitfalls, but I assume that you are aware of the requirements and limits of your current approach for your use case. IANAL, but for some use cases it is considered bad advice to only rely on the root level declarations and automated results (these usually only offer a first impression) - AFAIK re-checking this against all of the package code in a semi-automated fashion is considered the best approach. There have been studies which showed that not all maintainers are aware of such issues and incomplete/wrong declarations still exist, although at least for the actual *pypdf* package code I am not aware of such issues.

> PyPDF2 is no more supported and maintained. please check on pypdf if the issue is still valid. If not we will close it

This is not completely correct. Both the `PyPDF2` and the `pypdf` PyPI projects link to https://github.com/py-pdf/pypdf for their source and as already mentioned in the initial request, they refer to the same GitHub project ID as well. Especially due to using network APIs in this case, I do not think that this is an issue which is specific to PyPDF2.

**Comment by oaustegard** [comment] 2023-10-21 15:03
@stefan6419846 Much appreciated! While my parser was a fun (and still mostly useful) exercise, looking at pip-licenses it takes my own efforts and adds to them (though without the benefit of also checking Anaconda), both informative and validating, so thanks again for the pointer. :-)
