### ISSUE TITLE
Bug when getting images from a pdf

### ISSUE THREAD

**Issue by cylindrical2002** [py-pdf/pypdf#2124] opened 2023-08-28 14:50 UTC
Replace this: What happened? What were you trying to achieve?

## Environment

Which environment were you using when you encountered the problem?

```bash
conda create -n bank python=3.10
conda activate bank
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
pip install hanlp
pip install transformers
pip install opencc
pip install pypdf[full]
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader

reader = PdfReader("上海农村商业银行10.pdf")

number_of_pages = len(reader.pages)
print(number_of_pages)

# for page in reader.pages:
#     print(page.extract_text())
    
count = 0
    
for page in reader.pages:
    print(reader.pages.index(page))
    # print(page.extract_text())
    # if "/Annots" in page:
    #     for annot in page["/Annots"]:
    #         obj = annot.get_object()
    #         annotation = {"subtype": obj["/Subtype"], "location": obj["/Rect"]}
    #         print(annotation)
    if page.images is None:
        continue
    print(len(page.images))

    for image_file_object in page.images:
        # Ensure the image file object exists before attempting to use it
        if image_file_object is not None:
            with open(str(count) + image_file_object.name, "wb") as fp:
                fp.write(image_file_object.data)
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

[上海农村商业银行10.pdf](https://github.com/py-pdf/pypdf/files/12455580/10.pdf)

## Traceback
This is the complete Traceback I see:

```
TypeError                                 Traceback (most recent call last)
Cell In[4], line 25
     22     continue
     23 print(len(page.images))
---> 25 for image_file_object in page.images:
     26     # Ensure the image file object exists before attempting to use it
     27     if image_file_object is not None:
     28         with open(str(count) + image_file_object.name, "wb") as fp:

File [f:\Anaconda\envs\bank\lib\site-packages\pypdf\_page.py:2644](file:///F:/Anaconda/envs/bank/lib/site-packages/pypdf/_page.py:2644), in _VirtualListImages.__iter__(self)
   2642 def __iter__(self) -> Iterator[ImageFile]:
   2643     for i in range(len(self)):
-> 2644         yield self[i]

File [f:\Anaconda\envs\bank\lib\site-packages\pypdf\_page.py:2640](file:///F:/Anaconda/envs/bank/lib/site-packages/pypdf/_page.py:2640), in _VirtualListImages.__getitem__(self, index)
   2638 if index < 0 or index >= len_self:
   2639     raise IndexError("sequence index out of range")
-> 2640 return self.get_function(lst[index])

File [f:\Anaconda\envs\bank\lib\site-packages\pypdf\_page.py:544](file:///F:/Anaconda/envs/bank/lib/site-packages/pypdf/_page.py:544), in PageObject._get_image(self, id, obj)
    541         raise KeyError("no inline image can be found")
    542     return self.inline_images[id]
--> 544 imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
    545 extension, byte_stream = imgd[:2]
...
    918     ):
    919         _r = int(255 * (1 - _c / 255) * (1 - _k / 255))
    920         _g = int(255 * (1 - _m / 255) * (1 - _k / 255))

TypeError: object of type 'NoneType' has no len()
```

**Comment by stefan6419846** [comment] 2023-08-28 14:52
This seems to be a duplicate of #2110.

**Comment by cylindrical2002** [comment] 2023-08-28 14:53
> This seems to be a duplicate of #2110.

Did you find out how to solve it?

**Comment by stefan6419846** [comment] 2023-08-28 14:56
The handling for invalid lookups has to be reworked in PyPDF itself, so there is nothing you can do you from the outside (see the initial analysis in the other report). You might want to submit a corresponding PR attempting to fix this though.

**Comment by cylindrical2002** [comment] 2023-08-28 15:05
> The handling for invalid lookups has to be reworked in PyPDF itself, so there is nothing you can do you from the outside (see the initial analysis in the other report). You might want to submit a corresponding PR attempting to fix this though.

I got that, thank you!
Did you find this bug in early version of PyPDF?

**Comment by stefan6419846** [comment] 2023-08-28 15:09
Did you read the linked issue? You will see that I discovered this in version 3.15.2. Looking at the code, it might have been introduced in 3.10.0 with https://github.com/py-pdf/pypdf/commit/68e2cf0c25961f8ae5277dfc9ffa8978c00e3305#diff-185702ddcfbf2e4a9ef7106622bb77505eacae032966bba39c65ffb9cd0f9bc7

**Comment by cylindrical2002** [comment] 2023-08-28 15:14
I got your message, thank you!

**Comment by pubpub-zz** [comment] 2023-08-28 20:35
@stefan6419846 the issue is the same. good to have a public code for test.

**Closed** 2023-09-03 20:54 UTC

**Comment by Didi3333** [comment] 2024-01-16 07:03
Hi, i still have the bug with some PDF with version : 3.17.1

Invalid Lookup Table in {'/Subtype': '/Image', '/Filter': '/FlateDecode', '/BitsPerComponent': 8, '/ColorSpace': IndirectObject(10963, 0, 2463122516880), '/Width': 79, '/Height': 82, '/Type': '/XObject'}

[panda.pdf](https://github.com/py-pdf/pypdf/files/13946477/panda.pdf)
