### ISSUE TITLE
NotImplementedError: unsupported filter /JBIG2Decode

### ISSUE THREAD

**Issue by fredgido** [py-pdf/pypdf#951] opened 2022-06-06 08:46 UTC
Would be great support to extract JBIG2 image file from pdfs.
I intend to call as usual for image resources call .getData on a object with /JBIG2Decode decode filter and then write that to a file. Then, outside of PyPDF2 score, convert the saved file to a common format.

Here is pdfminer implementation:
https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/jbig2.py

[ItDoesntWorkScan.pdf](https://github.com/py-pdf/PyPDF2/files/8843068/ItDoesntWorkScan.pdf)

**Comment by pubpub-zz** [comment] 2023-07-20 18:58
closed as duplicate of #1989

**Closed by pubpub-zz** 2023-07-20 18:58 UTC
Labels: is-feature
