### ISSUE TITLE
A Bug of Free Text in Annotations

### ISSUE THREAD

**Issue by hachinoone** [py-pdf/pypdf#2433] opened 2024-02-02 04:37 UTC
The bug is observed in the official document in annotation part. The the font_color is always the same as the border_color, and cannot be changed. As the example shown in the document, the font_color is supposed to be green, but it remains blue, which is the same as border_color. 

```python3
from pypdf import PdfReader, PdfWriter
from pypdf.annotations import FreeText

# Fill the writer with the pages you want
pdf_path = os.path.join(RESOURCE_ROOT, "crazyones.pdf")
reader = PdfReader(pdf_path)
page = reader.pages[0]
writer = PdfWriter()
writer.add_page(page)

# Create the annotation and add it
annotation = FreeText(
    text="Hello World\nThis is the second line!",
    rect=(50, 550, 200, 650),
    font="Arial",
    bold=True,
    italic=True,
    font_size="20pt",
    font_color="00ff00",
    border_color="0000ff",
    background_color="cdcdcd",
)
writer.add_annotation(page_number=0, annotation=annotation)

# Write the annotated file to disk
with open("annotated-pdf.pdf", "wb") as fp:
    writer.write(fp)
```

**Comment by stefan6419846** [comment] 2024-02-02 07:00
Seems to be a duplicate of #2084?

**Comment by hachinoone** [comment] 2024-02-02 07:28
> Seems to be a duplicate of #2084?

Thanks. It seems that this issue is not sovled yet. I just want to add some text in PDF without using the border. Are there any other solutions?

**Comment by MartinThoma** [comment] 2024-02-04 10:02
As it's a duplicate, I'm closing this one in favor of #2084

**Closed by MartinThoma** 2024-02-04 10:02 UTC
Labels: workflow-annotation
