### ISSUE TITLE
PdfWriter does not support the strict parameter as stated in docs

### ISSUE THREAD

**Issue by claudep** [py-pdf/pypdf#2547] opened 2024-03-27 08:03 UTC
The docs currently says:

pypdf has three core objects and all of them have a strict parameter:
    PdfReader
    PdfWriter
    PdfMerger

## Environment

Which environment were you using when you encountered the problem?

Python 3.11 / pypdf 3.17.4

## Traceback

This is the partial traceback I see:
```
  File ".../pdf.py", line 27, in __init__
    self.merger = PdfWriter(strict=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PdfWriter.__init__() got an unexpected keyword argument 'strict'
```

**Comment by stefan6419846** [comment] 2024-03-27 08:08
This is a duplicate of #2479. The docs deployment is just not working at the moment, see #2484.

**Closed by stefan6419846** 2024-03-27 08:08 UTC

**Comment by claudep** [comment] 2024-03-27 08:11
I understand, sorry for the noise.
