### ISSUE TITLE
Wrong RTL language text direction when English numbers exist in the text

### ISSUE THREAD

**Issue by esraa-abdelmaksoud** [py-pdf/pypdf#1638] opened 2023-02-16 00:47 UTC
I was using pypdf to extract some Arabic text from a PDF. An [earlier problem](https://github.com/py-pdf/pypdf/issues/1589) related to the order of characters in words was fixed. However, when the text contains any English numbers, the order of sentences is totally mixed up. Fixing this is highly appreciated because Pypdf is the best package for extracting Arabic text so far. It's just critical to solve this because the majority of Arabic speakers use English numbers.

For example, the correct order of the following extracted line
![Screenshot from 2023-02-16 02-42-13](https://user-images.githubusercontent.com/73304837/219228911-6755ab60-1e37-4879-b578-703ae9e577b6.png)
should be
![Screenshot from 2023-02-16 02-43-04](https://user-images.githubusercontent.com/73304837/219228915-63c5ecf7-ea2c-426a-b99c-34d5b787511f.png)
and some of the numbers are not read as you can see.

Also, there is no space added at all between the last and first words when there is a great space between two texts in the same line as in the header of the pdf
![Screenshot from 2023-02-16 02-44-16](https://user-images.githubusercontent.com/73304837/219228916-900163e2-f77b-48be-aa54-eb4891fbf7fa.png)
is extracted as
![Screenshot from 2023-02-16 02-44-43](https://user-images.githubusercontent.com/73304837/219228918-a199dc4f-a2b1-430d-a68d-cd4b5bb54be0.png)

There are also 2 additional problems in the text above. The two-page numbers at the bottom of the PDF page are grabbed up and a part of the text is moved to the next line.

I already tried to get over this by extracting words and combining them, but there's no such option. Thanks for your contributions!

Ubuntu 22.04
pypdf 3.4.1

https://drive.google.com/file/d/1UAcXUqPpu1WVzlcdeuVBGWODAMmb3lkq/view?usp=sharing

```
from pypdf import PdfReader
reader = PdfReader(fname)
    full_text = ""
    for i, page in enumerate(reader.pages):
        text = page.extract_text()
        text += f"\n Page{i} + "\n"
        full_text += text
```

**Comment by pubpub-zz** [comment] 2023-02-16 19:42
@esraa-abdelmaksoud 
This looks like a duplicate of #1629 
Can you add your case to this thread, and also please provide the PDF file : without such data we can not conduct a proper analysis.

**Comment by pubpub-zz** [comment] 2023-02-16 19:42
closed as duplicate

**Closed by pubpub-zz** 2023-02-16 19:42 UTC
