### ISSUE TITLE
/JBIG2Decode is not supported

### ISSUE THREAD

**Issue by debater-coder** [py-pdf/pypdf#2502] opened 2024-03-06 00:50 UTC
I have been trying to retrieve images from a PDF generated by a scanner. It seems to be using the `JBIG2` codec, which is not supported.

## Environment

```bash
$ python -m platform
Windows-10-10.0.22631-SP0

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.0.1, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.2.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader, PdfWriter

reader = PdfReader("example.pdf")
writer = PdfWriter()
first_image = reader.pages[0].images[0]
```

## Traceback

This is the complete traceback I see:

```
Traceback (most recent call last):
  File "X:\isr10\pdf_assessment_tools\pdf_split.py", line 45, in _convert
    first_page = reader.pages[0].images[0]
                 ~~~~~~~~~~~~~~~~~~~~~~^^^
  File "X:\isr10\pdf_assessment_tools\.venv\Lib\site-packages\pypdf\_page.py", line 2421, in __getitem__
    return self.get_function(lst[index])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\isr10\pdf_assessment_tools\.venv\Lib\site-packages\pypdf\_page.py", line 496, in _get_image
    imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\isr10\pdf_assessment_tools\.venv\Lib\site-packages\pypdf\filters.py", line 749, in _xobj_to_image
    data = x_object_obj.get_data()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\isr10\pdf_assessment_tools\.venv\Lib\site-packages\pypdf\generic\_data_structures.py", line 881, in get_data
    decoded.set_data(b_(decode_stream_data(self)))
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\isr10\pdf_assessment_tools\.venv\Lib\site-packages\pypdf\filters.py", line 709, in decode_stream_data
    raise NotImplementedError(f"unsupported filter {filter_type}")
NotImplementedError: unsupported filter /JBIG2Decode

Process finished with exit code 1

```

**Comment by stefan6419846** [comment] 2024-03-06 06:25
This is a duplicate of #1989. Please have a look at the existing open issues before opening a new one.

**Closed by stefan6419846** 2024-03-06 06:25 UTC

**Comment by pubpub-zz** [comment] 2024-03-06 06:28
@debater-coder 
It would be appreciated if you could put the example file

**Comment by debater-coder** [comment] 2024-03-06 06:47
This is my example PDF: 
[example.pdf](https://github.com/py-pdf/pypdf/files/14505753/example.pdf)

Sorry, I searched 'JBIG' instead of 'JBIG2' and didn't find any open issues. I'll be more careful when checking for duplicate issues in the future.
