### ISSUE TITLE
pdf merge watermark file, part of the original file content is lost

### ISSUE THREAD

**Issue by yy4ever** [py-pdf/pypdf#2271] opened 2023-10-26 07:40 UTC
When I watermarked the pdf file, the file had three pages in total. After watermarking, the text content on the second and third pages was lost

## Environment

* Python 3.6.5
* pypdf==3.15.4

```bash
$ python -m platform
Linux-4.4.0-186-generic-x86_64-with-debian-stretch-sid

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.15.4, crypt_provider=('cryptography', '40.0.2'), PIL=8.4.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import hashlib
import os
import traceback

import reportlab.pdfbase.ttfonts
from pypdf import PdfReader, PdfWriter
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
import reportlab.pdfbase.ttfonts
from reportlab.lib.pagesizes import letter


def pdf_create_watermark(content):
    file_name = "mark.pdf"
    c = canvas.Canvas(file_name, pagesize=letter)
    c.translate(3 * cm, 12 * cm)
    try:
        reportlab.pdfbase.pdfmetrics.registerFont(
            reportlab.pdfbase.ttfonts.TTFont('yahei', "static/fonts/msyh.ttc"))
        c.setFont('yahei', 50)
    except:
        c.setFont("Helvetica", 30)
        content = "watermark"
    c.rotate(30)
    c.setFillColorRGB(0, 0, 0)
    c.setFillAlpha(0.05)
    width = c.stringWidth(content, 'yahei', 12)

    N_space_between_content = 5
    c.drawCentredString(0 * cm, 3 * cm, (content + " " * N_space_between_content) * 30)
    c.save()
    return file_name


def pdf_add_watermark(pdf_file_in, pdf_file_mark, pdf_file_out):
    writer = PdfWriter()
    input_stream = open(pdf_file_in, 'rb')
    reader = PdfReader(input_stream, strict=False)

    pageNum = len(reader.pages)

    pdf_watermark = PdfReader(open(pdf_file_mark, 'rb'), strict=False)
    for i in range(pageNum):
        page = reader.pages[i]
        page.merge_page(pdf_watermark.pages[0])
        try:
            writer.add_page(page)
        except Exception as e:
            print(traceback.format_exc())
    for page in writer.pages:
        page.compress_content_streams()
    writer.write(open(pdf_file_out, 'wb'))


def pdf_add_text_watermark(path, text):
    basedir = '.'
    pdf_file_in = 'raw.pdf'
    filename = os.path.basename(path).rsplit('.', maxsplit=1)[0]
    filepath = '.'
    filename = f"{filename}@watermark.pdf"
    pdf_file_out = os.path.join(basedir, f"{os.path.join(filepath, filename)}")
    if os.path.exists(pdf_file_out):
        return filename
    print(f"save water pdf to: {pdf_file_out}")
    pdf_file_mark = pdf_create_watermark(text)
    pdf_add_watermark(pdf_file_in, pdf_file_mark, pdf_file_out)
    return filename


pdf_add_text_watermark('raw.pdf', 'watertext')

```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!
#### raw pdf
![image](https://github.com/py-pdf/pypdf/assets/13010205/21c2e9f3-2d91-4ca4-892a-9028e7572bd8)

#### merged pdf
![image](https://github.com/py-pdf/pypdf/assets/13010205/1f78cf38-e9df-4f0d-9925-325310b299ae)

## Traceback

This is the complete Traceback I see:

```
# TODO: Your Traceback goes here (if applicable)
```

**Comment by stefan6419846** [comment] 2023-10-26 07:41
This seems to be a duplicate of #2260.

**Closed** 2023-10-26 08:56 UTC
