### ISSUE TITLE
blank thumbnails

### ISSUE THREAD

**Issue by petaflot** [py-pdf/pypdf#2315] opened 2023-11-27 15:58 UTC
I get blank thumbnails with tumbler, even after deleting the thumbnails cache directory.

is the embedded thumbnail generated properly? see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684485

## Environment

```bash
$ python -m platform
Linux-6.1.57-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_i7-4770K_CPU_@_3.50GHz-with-glibc2.37

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.16.4, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=9.5.0
```

## Code + PDF

This is a (not quite) minimal, complete example that shows the issue:

```python
#!/usr/bin/env python
"""
    take a number of (jpg?) files as arguments, convert them to PDF and merge into a single document

    resulting document is named after the first page with '.pdf' extension attached, all input and
    transition files are deleted
"""
from sys import argv
from subprocess import Popen
from os import remove

filenames = argv[1:]
pdfs = []

for filename in filenames:
    convert = Popen(['/usr/bin/convert', filename, (newname := filename.rsplit('.',1)[0]+'.pdf')])
    stdout, stderr = convert.communicate()
    pdfs.append(newname)

    if stdout:
        print(stdout)
    if stderr:
        raise Exception(stderr)

from pypdf import PdfMerger
merger = PdfMerger()
for pdf in pdfs:
    merger.append(pdf)

merger.write(f"{filenames[0]}.pdf")
merger.close()
for filename in filenames:
    remove(filename)
for pdf in pdfs:
    remove(pdf)
```

**Comment by stefan6419846** [comment] 2023-11-27 16:18
*PdfMerger* is deprecated in favor of *PdfWriter*: https://pypdf.readthedocs.io/en/latest/modules/PdfMerger.html

**Comment by petaflot** [comment] 2023-11-27 16:45
issue persists

**Comment by stefan6419846** [comment] 2023-11-27 16:49
Please provide your original PDF file(s) and the used code to reproduce your issue in this case.

**Comment by pubpub-zz** [comment] 2023-11-27 17:03
Thumbnails are not generated by pypdf : generating a thumbnail would mean interprete the pdf instruction and build a rendering image which is out of pypdf's scope. however this should not prevent most viewers to do the job.

**Comment by pubpub-zz** [comment] 2023-11-27 18:24
after a quick look in pdf reference 1.7, thumbnails are stored in `/Thumb` property of a page. Currently there is no direct access to the image.
You should be able to extract it passing the object as argument to `pypdf.filters._xobj_to_image()`

**Comment by petaflot** [comment] 2023-11-27 18:53
Ok I'm getting confused:
```python
#/usr/bin/env python
import pypdf
from sys import argv
with open(argv[1],'rb') as file:
    thumbnail = pypdf.filters._xobj_to_image()
    print(type(thumbnail))

```
results in 
```
(py311) meta@gentx ~/jpg_to_join/test $ ./test_thumbnail.py 2023-11-27_gros-tas_0000_verso.jpg.pdf
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/454.
from: too many arguments
./test_thumbnail.py: line 4: syntax error near unexpected token `('
./test_thumbnail.py: line 4: `with open(argv[1],'rb') as file:'
excerpt from `/etc/ImageMagick-7/policy.xml`:
```
<policymap>
  [...]
  <policy domain="{coder,module}" rights="read|write" pattern="{PS,PDF,XPS}" />
```

**Comment by petaflot** [comment] 2023-11-27 18:58
I'm still confused:
```python
#!/usr/bin/env python
import pypdf
from sys import argv
with open(argv[1],'rb') as file:
    thumbnail = pypdf.filters._xobj_to_image(file)
    print(type(thumbnail))
```
results in
```
Traceback (most recent call last):
  File "/home/meta/jpg_to_join/test/./test_thumbnail.py", line 5, in <module>
    thumbnail = pypdf.filters._xobj_to_image(file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meta/.local/python_venvs/py311/lib/python3.11/site-packages/pypdf/filters.py", line 744, in _xobj_to_image
    size = (x_object_obj[IA.WIDTH], x_object_obj[IA.HEIGHT])
            ~~~~~~~~~~~~^^^^^^^^^^
TypeError: '_io.BufferedReader' object is not subscriptable
```

**Comment by petaflot** [comment] 2023-11-27 19:02
I also tried
```python
import pypdf
from sys import argv
with open(argv[1],'rb') as file:
    pdf = pypdf.PdfReader(file)
    xobj = pypdf.filters._xobj_to_image(pdf)
    print(type(xobj))
```
and got
```
Traceback (most recent call last):
  File "/home/meta/jpg_to_join/test/./test_thumbnail.py", line 6, in <module>
    xobj = pypdf.filters._xobj_to_image(pdf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meta/.local/python_venvs/py311/lib/python3.11/site-packages/pypdf/filters.py", line 744, in _xobj_to_image
    size = (x_object_obj[IA.WIDTH], x_object_obj[IA.HEIGHT])
            ~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'PdfReader' object is not subscriptable
```

**Comment by pubpub-zz** [comment] 2023-11-27 21:29
thumbnails are in the pages:
(draft not tested)
```
import pypdf
from sys import argv
with open(argv[1],'rb') as file:
    pdf = pypdf.PdfReader(file)
    for p in pdf.pages:
        if "/Thumb" in p:
            xobj = pypdf.filters._xobj_to_image(p["/Thumb"])
           print(type(xobj))
```

**Comment by pubpub-zz** [comment] 2023-11-29 22:02
@petaflot 
can we close this thread ?

**Comment by petaflot** [comment] 2023-11-30 11:48
so.. I tried on one file, I got two (!) thumbnails that are 1x1 pixels in dimension.

> can we close this thread ?

not quite.. we've gone a good step further, but the thumbnails need to be replaced with something that matches the content

**Comment by pubpub-zz** [comment] 2023-11-30 19:05
with the following test file:
https://github.com/py-pdf/pypdf/files/12352793/kim2002.pdf

```
import pypdf
rr = pypdf.PdfReader("iss2089.pdf")
for p in rr.pages:
    pypdf.filters._xobj_to_image(p["/Thumb"])[2].show()  # the pillow image is in third position
```

shows all the thumbnails

https://github.com/py-pdf/pypdf/blob/main/resources/crazyones.pdf 
does not contains thumbnails:
`"/Thumb" in pypdf.PdfReader("crazyones.pdf").pages[0]` -> False

however standard viewers are rebuilding them automatically (eg with pdf.js):
![image](https://github.com/py-pdf/pypdf/assets/4083478/0c787bfc-2ba8-4861-8ebb-9472fbca2f60)

This should be OK

**Comment by pubpub-zz** [comment] 2024-02-25 12:40
@petaflot 
can you provide update
else we will have to close this issue

**Comment by petaflot** [comment] 2024-02-25 13:03
> with the following test file: https://github.com/py-pdf/pypdf/files/12352793/kim2002.pdf
> 
> ```
> import pypdf
> rr = pypdf.PdfReader("iss2089.pdf")
> for p in rr.pages:
>     pypdf.filters._xobj_to_image(p["/Thumb"])[2].show()  # the pillow image is in third position
> ```
> shows all the thumbnails

beyond the code that has a reference to the wrong filename, I also get the thumbnail. this is just for a demonstration that it works, correct?


> https://github.com/py-pdf/pypdf/blob/main/resources/crazyones.pdf does not contains thumbnails: `"/Thumb" in pypdf.PdfReader("crazyones.pdf").pages[0]` -> False
> 
> however standard viewers are rebuilding them automatically (eg with pdf.js): 
> 
> This should be OK

your `crazyones.pdf` file does not even appear to be a PDF:

```
(py311) meta@gentx /tmp $ file kim2002.pdf
kim2002.pdf: PDF document, version 1.2, 12 page(s)
(py311) meta@gentx /tmp $ file crazyones.pdf
crazyones.pdf: JSON text data
(py311) meta@gentx /tmp $ mupdf crazyones.pdf
warning: trying to repair broken xref
warning: repairing PDF document
[Error Dialog: "No objects found" ; click OK]
warning: name is too long
warning: ... repeated 3 times...
```

just because *some* viewers fix the thumbnail doesn't mean *all* viewers will ; because *sometimes* a viewer may have write access to the file does not mean we can rely on a viewer to fix a broken file that may be generated on a headless machine and immediately archived or published on a read-only basis.

**Comment by pubpub-zz** [comment] 2024-02-25 13:36
> your `crazyones.pdf` file does not even appear to be a PDF:

the link was pointing to the github page. the actual file is available "in" the download

> just because _some_ viewers fix the thumbnail doesn't mean _all_ viewers will ; because _sometimes_ a viewer may have write access to the file does not mean we can rely on a viewer to fix a broken file that may be generated on a headless machine and immediately archived or published on a read-only basis.

What is expected is to generate the thumbnails in memory, not to modify the files.
regenerating thumbnails would mean first to parse the page and generate an image from it. This is out of pypdf capabilities.

**Comment by petaflot** [comment] 2024-02-25 13:56
> > your `crazyones.pdf` file does not even appear to be a PDF:
> 
> the link was pointing to the github page. the actual file is available "in" the download
> 
> > just because _some_ viewers fix the thumbnail doesn't mean _all_ viewers will ; because _sometimes_ a viewer may have write access to the file does not mean we can rely on a viewer to fix a broken file that may be generated on a headless machine and immediately archived or published on a read-only basis.
> 
> What is expected is to generate the thumbnails in memory, not to modify the files. regenerating thumbnails would mean first to parse the page and generate an image from it.

so what you mean is "what is expected is that the file be read and parsed so the first page can be converted to a thumbnail  stored only in memory and that thumbnail will be lost after a reboot, and this must be repeated for every single user that *might* eventually want to see the thumbnail?

this makes little sense : if so, why can thumbnails be embedded in a PDF file at all?


>  This is out of pypdf capabilities.

if thumbnails can be embedded in PDFs files, then this should be within pypdf's capabilities ; at the very least, pypdf sould be able to use another lib that has this capability in order to properly embed the thumbnail

**Comment by pubpub-zz** [comment] 2024-02-25 14:02
> this makes little sense : if so, why can thumbnails be embedded in a PDF file at all?

They can : the images are stored in /Thumb properties

> if thumbnails can be embedded in PDFs files, then this should be within pypdf's capabilities ; at the very least, pypdf sould be able to use another lib that has this capability in order to properly embed the thumbnail

The issue is not to store the image but to generate the image : you need a viewer such as ghostviewer to do this

**Comment by stefan6419846** [comment] 2024-02-25 14:12
Could we please have a common discussion base here? In https://github.com/py-pdf/pypdf/issues/2315#issuecomment-1833612460 it is mentioned that *pypdf* generates thumbnails which have a size of one pixel in total. Could you please provide a corresponding PDF file which shows this actual issue and how you generated it and how you retrieved the corresponding thumbnail? I am having trouble to follow this discussion otherwise. If *pypdf* really generates invalid thumbnails, this might be a bug which deserves fixing.

Besides this: If you think you know a suitable solution for generating correct thumbnails, you are always invited to propose a corresponding PR with either an integrated solution or some code example for the docs on how to add thumbnails if someone requires them out-of-the-box. Nevertheless, this will always involve external rendering engines like Ghostscript (as in our watermarking tests) or Poppler (like *pdf2image* does) which have to be installed on the system as *pypdf* works on the byte level and performs no rendering itself.

**Comment by stefan6419846** [comment] 2024-02-25 14:40
I just took a simple example of my profile image and an old screenshot, converted them to PDF using `convert image.png image.pdf` (with ImageMagick 6.9.11-60) and then run the following code:

```
import pypdf
from sys import argv


merger = pypdf.PdfWriter()
for pdf in argv[1:]:
    merger.append(pdf)
for pdf in argv[1:]:
    merger.append(pdf)
merger.write("merged.pdf")


with open("merged.pdf",'rb') as file:
    pdf = pypdf.PdfReader(file)
    for p in pdf.pages:
        if "/Thumb" in p:
           xobj = pypdf.filters._xobj_to_image(p["/Thumb"])
           extension, data, image = xobj
           image.save(f"{p.page_number}{extension}")

```

This generates four correct files which represent the thumbnails.

**Comment by petaflot** [comment] 2024-02-25 14:42
as stated in my first post: 
```
   convert = Popen(['/usr/bin/convert', filename, (newname := filename.rsplit('.',1)[0]+'.pdf')])
```
take *any* [jpeg image](https://github.com/py-pdf/pypdf/assets/32837871/a58ac35a-dea9-4613-96be-b782aa47f425) (this came out of my scanner, with xsane) for example and you have [your PDF](https://github.com/py-pdf/pypdf/files/14396700/test.pdf)

This makes me realize I might need to file a bug with the guys who are maintaining `convert`, though...

**Closed as completed** 2024-02-25 14:48 UTC
Labels: needs-pdf

**Comment by petaflot** [comment] 2024-02-25 14:49
https://github.com/ImageMagick/ImageMagick/issues/7130
